name: base
description: app for traveling
publish_to: 'none'
version: 3.0.24+88

environment:
  sdk: '>=3.1.0 <4.0.0'

dependency_overrides:
  intl: ^0.18.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.14
  # // TODO: UX/UI
  flutter_easyloading: ^3.0.5
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  fluttericon: ^2.0.0
  shimmer: ^3.0.0
  group_button: ^5.3.3
  skeletonizer: ^0.8.0
  pinput: ^3.0.1
  fancy_shimmer_image: ^2.0.3
  carousel_slider: ^4.2.1
  custom_refresh_indicator: ^3.0.0
  photo_view_x: ^0.0.3
  expandable_text:
    path: packages/expandable_text
  timeago: ^3.6.0
  gap: ^3.0.1
  grouped_list: ^5.1.2
  # // TODO: Service 
  shared_preferences: ^2.2.2 
  talker_flutter: ^3.5.4
  talker_dio_logger: ^2.3.1
  device_preview: ^1.1.0
  permission_handler: ^11.1.0
  talker_bloc_logger: ^2.2.1
  flutter_local_notifications: ^16.1.0
  huawei_push: ^6.11.0+300
  geolocator: ^10.1.0
  google_api_availability: ^5.0.0
  flutter_flavor: ^3.1.3
  url_launcher: ^6.2.1
  notification_permissions: ^0.6.1
  upgrader: ^8.3.0
  image_picker: ^1.0.4
  device_uuid: ^0.0.4
  visibility_detector: ^0.4.0+2
  # // TODO: State Management
  provider: ^6.1.1
  dio: ^5.3.4
  path_provider: ^2.1.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.8.0
  latlong2: ^0.9.0
  go_router: ^12.1.1
  flutter_isolate: ^2.0.4
  flutter_secure_storage: ^9.0.0
  textfield_search: ^0.10.0
  qr_code_scanner: ^1.0.1
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.5
  firebase_analytics: ^10.7.1
  firebase_performance: ^0.9.3+5
  firebase_messaging: ^14.7.5
  pull_to_refresh: ^2.0.0
  expandable: ^5.0.1
  path: ^1.8.3
  base_package:
    path: packages/base_package
  collection: ^1.18.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  chewie: ^1.7.1
  video_player: ^2.8.1
  flutter_keyboard_visibility: ^5.4.1
  flutter_sliding_up_panel: ^2.1.1
  easy_refresh: ^3.3.2+4
  extended_nested_scroll_view: ^6.1.2
  path_drawing: ^1.0.1
  app_links: ^3.4.5
  fresh_dio: ^0.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.4
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  bloc_test: ^9.1.5
  logger: ^2.0.2+1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/videos/

  fonts:
    - family: 'Mulish'
      fonts:
        - asset: assets/fonts/Mulish-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Mulish-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 900
    - family: RFDewi
      fonts:
        - asset: assets/fonts/RFDewi/RFDewi-Thin.ttf
          weight: 100
        - asset: assets/fonts/RFDewi/RFDewi-Ultralight.ttf
          weight: 200
        - asset: assets/fonts/RFDewi/RFDewi-Light.ttf
          weight: 300
        - asset: assets/fonts/RFDewi/RFDewi-Regular.ttf
          weight: 400
        - asset: assets/fonts/RFDewi/RFDewi-Semibold.ttf
          weight: 500
        - asset: assets/fonts/RFDewi/RFDewi-Semibold.ttf
          weight: 600
        - asset: assets/fonts/RFDewi/RFDewi-Bold.ttf
          weight: 700
        - asset: assets/fonts/RFDewi/RFDewi-Ultrabold.ttf
          weight: 800
        - asset: assets/fonts/RFDewi/RFDewi-Black.ttf
          weight: 900
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerif/PTSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/PTSerif/PTSerif-Bold.ttf
          weight: 700
    - family: Bell MT
      fonts:
        - asset: assets/fonts/BellMT.ttf
          weight: 400
    - family: loca_icons
      fonts:
        - asset: assets/fonts/loca_icons.ttf
    - family: qr_scanner
      fonts:
        - asset: assets/fonts/qr_scanner.ttf